apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-gpou
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-gpou
    app.kubernetes.io/part-of: andy-pacman
  name: pacman-gpou
  namespace: abrarenrh-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: pacman-gpou
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: pacman-gpou
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d4e3037dc5a6de5540276680c7742d9c7526a0ceeba9fd7dc63ae8ebdb8886ce
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
