apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-gpou
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-gpou
    app.kubernetes.io/part-of: andy-pacman
  name: pacman-gpou
  namespace: abrarenrh-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: pacman-gpou
status:
  loadBalancer: {}
